"""empty message

Revision ID: 449c601ca322
Revises: b62bf566ec09
Create Date: 2024-06-04 23:49:36.414937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '449c601ca322'
down_revision = 'b62bf566ec09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
